### ISSUE TITLE
Duplicate Symbol User

### ISSUE THREAD

**Issue by ErwanHesry** [STIMSHOP/SDK-stimshop-iOS#1]
Hi,

I tried to implement the SDK. Pretty easy, great job.
However, when I want to build my app, I got an error message which says me that there are some duplicate symbols User.
I use a CoreData db in my app with an entity called User. I think it's a pretty common name for a class in any app.
Wouldn't be your class named STM_User or a kind of? Is there a way to rename it? My User class is used throught the entire project.

Here is in the build log:

```
duplicate symbol _OBJC_CLASS_$_User in:
    /[PROJECT_BUILD_PATH]/Debug-iphoneos/[TARGET].build/Objects-normal/arm64/User+CoreDataClass.o
    /[PROJECT_SOURCE_PATH]/External/Stimshop/libStimshop_SDK.a(User.o)
duplicate symbol _OBJC_METACLASS_$_User in:
    /[PROJECT_BUILD_PATH]/Debug-iphoneos/[TARGET].build/Objects-normal/arm64/User+CoreDataClass.o
    /[PROJECT_SOURCE_PATH]/External/Stimshop/libStimshop_SDK.a(User.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by STIMSHOP** [comment]
Dear Erwan,

As you mentioned, we have a class named User in the SDK and it is used a lot in many dependencies.
As XCode does not provide convenient tool to change this name, it is not easy to do right now. But You got a point, User is a very common name and I will consider this prefix idea.
Check future revision for this.

**Comment by ErwanHesry** [comment]
Thanks for the update 3.2.
